services:
  mongodb:
    image: mongo:latest
    container_name: yjs-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!123
    volumes:
      - mongodb_data:/data/db

  websocket-server:
    image: yinlin124/collaborative-editor-backend:latest
    container_name: yjs-websocket-server
    restart: always
    ports:
      - "${PORT:-1234}:${PORT:-1234}"
    environment:
      HOST: 0.0.0.0
      PORT: ${PORT:-1234}
      MONGODB_URL: mongodb://admin:admin!123@mongodb:27017/?authSource=admin
      MONGODB_DB: tinyeditor
      MONGODB_COLLECTION: documents
    depends_on:
      - mongodb

volumes:
  mongodb_data:
